# Generated by Django 4.1.7 on 2023-06-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcevent',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gcevent',
            name='poster',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
