# Generated by Django 4.1.7 on 2023-06-28 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0004_alter_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcevent',
            name='end_timeline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gcevent',
            name='start_timeline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
