# Generated by Django 4.1.7 on 2023-07-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0006_alter_score_hostel_alter_score_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcevent',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
