# Generated by Django 4.2.2 on 2023-07-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0013_hostel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='number',
        ),
        migrations.AddField(
            model_name='hostel',
            name='tittle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
