# Generated by Django 4.0.4 on 2023-09-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0014_remove_hostel_number_hostel_tittle'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcevent',
            name='club',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gcevent',
            name='gc_genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gcevent',
            name='prep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
