# Generated by Django 3.0.5 on 2023-11-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0016_auto_20231009_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
